  
name: CI


on:
  workflow_dispatch:


#on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: pytest

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          # If lock file missing, generate it
          if [ ! -f package-lock.json ]; then
            npm install  --package-lock-only
          fi
          npm install
 
      - name: Run frontend tests
        run: |
          npm test -- --coverage --watchAll=false --passWithNoTests

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build backend Docker image
        run: |
          docker build \
            -f infra/docker/backend.Dockerfile \
            -t fraud-shield-backend .

      - name: Build frontend Docker image
        run: |
          docker build \
            -f infra/docker/frontend.Dockerfile \
            -t fraud-shield-frontend .
